/* tslint:disable */
/* eslint-disable */
/**
 * DefaultApiTemplate
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface SignatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest
 */
export interface SignatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof SignatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest
     */
    'password'?: string | null;
}
/**
 * 
 * @export
 * @interface SignatureRecognitionWebApiControllersAuthenticationResponsesLoginResponse
 */
export interface SignatureRecognitionWebApiControllersAuthenticationResponsesLoginResponse {
    /**
     * 
     * @type {string}
     * @memberof SignatureRecognitionWebApiControllersAuthenticationResponsesLoginResponse
     */
    'refreshToken'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignatureRecognitionWebApiControllersAuthenticationResponsesLoginResponse
     */
    'accessToken'?: string | null;
}
/**
 * 
 * @export
 * @interface SignatureRecognitionWebApiControllersSignaturesResponsesGetSignaturesInfoResponse
 */
export interface SignatureRecognitionWebApiControllersSignaturesResponsesGetSignaturesInfoResponse {
    /**
     * 
     * @type {number}
     * @memberof SignatureRecognitionWebApiControllersSignaturesResponsesGetSignaturesInfoResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof SignatureRecognitionWebApiControllersSignaturesResponsesGetSignaturesInfoResponse
     */
    'name'?: string | null;
}

/**
 * AuthenticationApi - axios parameter creator
 * @export
 */
export const AuthenticationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Войти.
         * @param {SignatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest} [signatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest] Данные для входа.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authenticationLoginPost: async (signatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest?: SignatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Authentication/Login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Регистрация.
         * @param {string} [userName] Имя пользователя
         * @param {string} [email] Почта.
         * @param {string} [password] Пароль.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authenticationRegisterPost: async (userName?: string, email?: string, password?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Authentication/Register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userName !== undefined) {
                localVarQueryParameter['userName'] = userName;
            }

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }

            if (password !== undefined) {
                localVarQueryParameter['password'] = password;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationApi - functional programming interface
 * @export
 */
export const AuthenticationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthenticationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Войти.
         * @param {SignatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest} [signatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest] Данные для входа.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authenticationLoginPost(signatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest?: SignatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignatureRecognitionWebApiControllersAuthenticationResponsesLoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authenticationLoginPost(signatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.authenticationLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Регистрация.
         * @param {string} [userName] Имя пользователя
         * @param {string} [email] Почта.
         * @param {string} [password] Пароль.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authenticationRegisterPost(userName?: string, email?: string, password?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authenticationRegisterPost(userName, email, password, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.authenticationRegisterPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthenticationApi - factory interface
 * @export
 */
export const AuthenticationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthenticationApiFp(configuration)
    return {
        /**
         * 
         * @summary Войти.
         * @param {SignatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest} [signatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest] Данные для входа.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authenticationLoginPost(signatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest?: SignatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<SignatureRecognitionWebApiControllersAuthenticationResponsesLoginResponse> {
            return localVarFp.authenticationLoginPost(signatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Регистрация.
         * @param {string} [userName] Имя пользователя
         * @param {string} [email] Почта.
         * @param {string} [password] Пароль.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authenticationRegisterPost(userName?: string, email?: string, password?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.authenticationRegisterPost(userName, email, password, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationApi - object-oriented interface
 * @export
 * @class AuthenticationApi
 * @extends {BaseAPI}
 */
export class AuthenticationApi extends BaseAPI {
    /**
     * 
     * @summary Войти.
     * @param {SignatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest} [signatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest] Данные для входа.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public authenticationLoginPost(signatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest?: SignatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).authenticationLoginPost(signatureRecognitionWebApiControllersAuthenticationRequestsLoginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Регистрация.
     * @param {string} [userName] Имя пользователя
     * @param {string} [email] Почта.
     * @param {string} [password] Пароль.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public authenticationRegisterPost(userName?: string, email?: string, password?: string, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).authenticationRegisterPost(userName, email, password, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SignaturesApi - axios parameter creator
 * @export
 */
export const SignaturesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Добавить несколько подписей.
         * @param {Array<File>} [files] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSignaturesAddPost: async (files?: Array<File>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Signatures/Add`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication oauth2 required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (files) {
                files.forEach((element) => {
                    localVarFormParams.append('files', element as any);
                })
            }

    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Добавить подпись.
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSignaturesAddSignaturePost: async (file?: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Signatures/AddSignature`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication oauth2 required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Удалить все подписи пользователя.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSignaturesAllDeleteDelete: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Signatures/All/Delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Удалить подпись.
         * @param {number} [fileId] Идентификатор файла подписи.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSignaturesDeleteSignatureDelete: async (fileId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Signatures/DeleteSignature`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (fileId !== undefined) {
                localVarQueryParameter['fileId'] = fileId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Находит подписи на изображении.
         * @param {number} [fileId] Id изображения на котором надо найти подписи.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSignaturesFileDetectSignaturesPost: async (fileId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Signatures/File/DetectSignatures`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (fileId !== undefined) {
                localVarQueryParameter['fileId'] = fileId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получить изображение подписи.
         * @param {number} [fileId] Идентификатор файла подписи.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSignaturesGetSignatureGet: async (fileId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Signatures/GetSignature`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (fileId !== undefined) {
                localVarQueryParameter['fileId'] = fileId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получить информацию о подписях пользователя.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSignaturesInformationGetGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Signatures/Information/Get`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SignaturesApi - functional programming interface
 * @export
 */
export const SignaturesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SignaturesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Добавить несколько подписей.
         * @param {Array<File>} [files] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSignaturesAddPost(files?: Array<File>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSignaturesAddPost(files, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SignaturesApi.apiSignaturesAddPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Добавить подпись.
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSignaturesAddSignaturePost(file?: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSignaturesAddSignaturePost(file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SignaturesApi.apiSignaturesAddSignaturePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Удалить все подписи пользователя.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSignaturesAllDeleteDelete(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSignaturesAllDeleteDelete(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SignaturesApi.apiSignaturesAllDeleteDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Удалить подпись.
         * @param {number} [fileId] Идентификатор файла подписи.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSignaturesDeleteSignatureDelete(fileId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSignaturesDeleteSignatureDelete(fileId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SignaturesApi.apiSignaturesDeleteSignatureDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Находит подписи на изображении.
         * @param {number} [fileId] Id изображения на котором надо найти подписи.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSignaturesFileDetectSignaturesPost(fileId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSignaturesFileDetectSignaturesPost(fileId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SignaturesApi.apiSignaturesFileDetectSignaturesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получить изображение подписи.
         * @param {number} [fileId] Идентификатор файла подписи.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSignaturesGetSignatureGet(fileId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSignaturesGetSignatureGet(fileId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SignaturesApi.apiSignaturesGetSignatureGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получить информацию о подписях пользователя.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSignaturesInformationGetGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SignatureRecognitionWebApiControllersSignaturesResponsesGetSignaturesInfoResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSignaturesInformationGetGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SignaturesApi.apiSignaturesInformationGetGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SignaturesApi - factory interface
 * @export
 */
export const SignaturesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SignaturesApiFp(configuration)
    return {
        /**
         * 
         * @summary Добавить несколько подписей.
         * @param {Array<File>} [files] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSignaturesAddPost(files?: Array<File>, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiSignaturesAddPost(files, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Добавить подпись.
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSignaturesAddSignaturePost(file?: File, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiSignaturesAddSignaturePost(file, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Удалить все подписи пользователя.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSignaturesAllDeleteDelete(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiSignaturesAllDeleteDelete(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Удалить подпись.
         * @param {number} [fileId] Идентификатор файла подписи.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSignaturesDeleteSignatureDelete(fileId?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiSignaturesDeleteSignatureDelete(fileId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Находит подписи на изображении.
         * @param {number} [fileId] Id изображения на котором надо найти подписи.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSignaturesFileDetectSignaturesPost(fileId?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiSignaturesFileDetectSignaturesPost(fileId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получить изображение подписи.
         * @param {number} [fileId] Идентификатор файла подписи.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSignaturesGetSignatureGet(fileId?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiSignaturesGetSignatureGet(fileId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получить информацию о подписях пользователя.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSignaturesInformationGetGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<SignatureRecognitionWebApiControllersSignaturesResponsesGetSignaturesInfoResponse>> {
            return localVarFp.apiSignaturesInformationGetGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SignaturesApi - object-oriented interface
 * @export
 * @class SignaturesApi
 * @extends {BaseAPI}
 */
export class SignaturesApi extends BaseAPI {
    /**
     * 
     * @summary Добавить несколько подписей.
     * @param {Array<File>} [files] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SignaturesApi
     */
    public apiSignaturesAddPost(files?: Array<File>, options?: RawAxiosRequestConfig) {
        return SignaturesApiFp(this.configuration).apiSignaturesAddPost(files, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Добавить подпись.
     * @param {File} [file] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SignaturesApi
     */
    public apiSignaturesAddSignaturePost(file?: File, options?: RawAxiosRequestConfig) {
        return SignaturesApiFp(this.configuration).apiSignaturesAddSignaturePost(file, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Удалить все подписи пользователя.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SignaturesApi
     */
    public apiSignaturesAllDeleteDelete(options?: RawAxiosRequestConfig) {
        return SignaturesApiFp(this.configuration).apiSignaturesAllDeleteDelete(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Удалить подпись.
     * @param {number} [fileId] Идентификатор файла подписи.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SignaturesApi
     */
    public apiSignaturesDeleteSignatureDelete(fileId?: number, options?: RawAxiosRequestConfig) {
        return SignaturesApiFp(this.configuration).apiSignaturesDeleteSignatureDelete(fileId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Находит подписи на изображении.
     * @param {number} [fileId] Id изображения на котором надо найти подписи.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SignaturesApi
     */
    public apiSignaturesFileDetectSignaturesPost(fileId?: number, options?: RawAxiosRequestConfig) {
        return SignaturesApiFp(this.configuration).apiSignaturesFileDetectSignaturesPost(fileId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получить изображение подписи.
     * @param {number} [fileId] Идентификатор файла подписи.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SignaturesApi
     */
    public apiSignaturesGetSignatureGet(fileId?: number, options?: RawAxiosRequestConfig) {
        return SignaturesApiFp(this.configuration).apiSignaturesGetSignatureGet(fileId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получить информацию о подписях пользователя.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SignaturesApi
     */
    public apiSignaturesInformationGetGet(options?: RawAxiosRequestConfig) {
        return SignaturesApiFp(this.configuration).apiSignaturesInformationGetGet(options).then((request) => request(this.axios, this.basePath));
    }
}



